[phases.setup]
nixPkgs = ["python312", "ffmpeg", "xvfb-run"]
nixpacksVersion = "1.24.0"  # Attempted to force a newer base with GLIBC 2.36+

[phases.build]
cmds = [". /opt/venv/bin/activate && pip install playwright"]

[start]
cmd = "Xvfb :0 -screen 0 1920x1080x24 & gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 300 app:app"
