buildImage = "ubuntu:24.04"
[phases.setup]
aptPkgs = ["python312", "ffmpeg", "xvfb"]
[phases.install]
cmds = ["pip install -r requirements.txt"]
[phases.build]
cmds = ["playwright install chromium"]
