buildImage = "ghcr.io/railwayapp/nixpacks:ubuntu-2204"

[phases.setup]
nixPkgs = ["python312", "ffmpeg", "xvfb-run"]
cmds = ["curl -fsSL https://nixos.org/nix/install | sh", "nix-env -i python3.12 ffmpeg xvfb-run"]
aptPkgs = ["xvfb"]

[phases.build]
cmds = [
". /opt/venv/bin/activate", 
"pip install -r requirements.txt",
"pip install pytest-playwright",
"playwright install chromium"
]

[start]
cmd = "Xvfb :0 -screen 0 1920x1080x24 & gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 300 app:app"
