buildImage = "usagiakimbo/custom-nix-ubuntu:24.04"

[phases.install]
cmds = ["python3 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = [". /opt/venv/bin/activate && playwright install chromium"]

[phases.build]
cmds = [". /opt/venv/bin/activate && playwright install chromium"]
