[phases.setup]
nixPkgs = ["python39", "ffmpeg", "xvfb"]

[phases.build]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]

[start]
cmd = "Xvfb :0 -screen 0 1920x1080x24 & gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 300 app:app"
