# Use the custom image with FFmpeg and x11grab already included
buildImage = "usagiakimbo/custom-nix-ubuntu:24.04-x11grab"

# No providers specified, assuming you're handling the app setup manually
providers = []

[phases.setup]
# Additional apt packages for your app (e.g., Playwright, Chromium deps)
aptPkgs = [
  "libglib2.0-0", "libnss3", "libcups2", "libdbus-1-3", "libatk1.0-0",
  "libatk-bridge2.0-0", "libx11-6", "libxcomposite1", "libxdamage1",
  "libxext6", "libxfixes3", "libxrandr2", "libgbm1", "libxcb1",
  "libxkbcommon0", "libpango-1.0-0", "libcairo2", "libasound2t64",
  "libatspi2.0-0", "libexpat1", "libstdc++6", "apt-utils",
  "python3-pip", "python3-venv"  # Already in base image, but ensuring pip/venv
]
cmds = [
  "apt-get update",
  "apt-get install -y --no-install-recommends ${APT_PKGS}",
  # Configure X11 and setup dirs (still needed for runtime)
  "dpkg-reconfigure -f noninteractive x11-common",
  "mkdir -p /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix",
  "touch /tmp/.Xauthority && chmod 600 /tmp/.Xauthority",
  "ldconfig"
]

[phases.build]
cmds = [
  # Set up Python virtual env and install dependencies
  "/usr/bin/python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  # Install Playwright and Chromium
  ". /opt/venv/bin/activate && playwright install chromium"
]
